name: Supabase Deploy (Staging)

on:
  push:
    branches:
      - staging
    paths:
      - "infrastructure/supabase"
  workflow_dispatch:

jobs:
  config-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure/supabase/staging
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.STAG_SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.STAG_SUPABASE_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase config push
